[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.269619+01:00] request.INFO: Matched route "contao_managerapi_server_adminuser__invoke". {"route":"contao_managerapi_server_adminuser__invoke","route_parameters":{"_route":"contao_managerapi_server_adminuser__invoke","_controller":"_ContaoManager\\Contao\\ManagerApi\\Controller\\Server\\AdminUserController"},"request_uri":"https://duc-contao-5.local/contao-manager.phar.php/api/server/admin-user","method":"GET"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.300272+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":4} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.304697+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.305103+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.306325+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.306774+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.306780+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.309233+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.309249+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.309264+01:00] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.312603+01:00] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.321488+01:00] security.INFO: Guard authentication successful! {"token":{"_ContaoManager\\Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken":"PostAuthenticationGuardToken(user=\"duc\", authenticated=true, roles=\"ROLE_ADMIN\")"},"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.322362+01:00] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:48.322368+01:00] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[21-Nov-2024 17:08:50 CET] [2024-11-21T17:08:50.585799+01:00] app.CRITICAL: Uncaught PHP Exception _ContaoManager\Symfony\Component\Process\Exception\ProcessFailedException: "The command "'/usr/local/bin/php' '-q' '-dmax_execution_time=0' '-dmemory_limit=-1' '-ddisplay_errors=0' '-ddisplay_startup_errors=0' '-derror_reporting=0' '-dallow_url_fopen=1' '-ddisable_functions=' '-ddate.timezone=CET' '/shared/httpd/duc-contao-5/vendor/contao/manager-bundle/bin/contao-console' 'contao:user:list' '--format=json' '--column=username' '--column=name' '--column=admin' '--column=dateAdded' '--column=lastLogin' '--no-interaction'" failed.  Exit Code: 255(Unknown error)  Working directory: /shared/httpd/duc-contao-5  Output: ================   Error Output: ================ 17:08:50 CRITICAL  [console] Error thrown while running command "contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction". Message: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'contao53.tl_user' doesn't exist" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction","message" => "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'contao53.tl_user' doesn't exist"]  In ExceptionConverter.php line 49:                                                                                   An exception occurred while executing a query: SQLSTATE[42S02]: Base table      or view not found: 1146 Table 'contao53.tl_user' doesn't exist                                                                                                 In Exception.php line 28:                                                                                   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'contao53.tl_user     ' doesn't exist                                                                                                                                                In Connection.php line 71:                                                                                   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'contao53.tl_user     ' doesn't exist                                                                                                                                                contao:user:list [--column COLUMN] [--admins] [--format FORMAT]  " at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/api/Process/ContaoConsole.php line 162 {"exception":"[object] (_ContaoManager\\Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"'/usr/local/bin/php' '-q' '-dmax_execution_time=0' '-dmemory_limit=-1' '-ddisplay_errors=0' '-ddisplay_startup_errors=0' '-derror_reporting=0' '-dallow_url_fopen=1' '-ddisable_functions=' '-ddate.timezone=CET' '/shared/httpd/duc-contao-5/vendor/contao/manager-bundle/bin/contao-console' 'contao:user:list' '--format=json' '--column=username' '--column=name' '--column=admin' '--column=dateAdded' '--column=lastLogin' '--no-interaction'\" failed.\n\nExit Code: 255(Unknown error)\n\nWorking directory: /shared/httpd/duc-contao-5\n\nOutput:\n================\n\n\nError Output:\n================\n17:08:50 CRITICAL  [console] Error thrown while running command \"contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction\". Message: \"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'contao53.tl_user' doesn't exist\" [\"exception\" => Doctrine\\DBAL\\Exception\\TableNotFoundException { …},\"command\" => \"contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction\",\"message\" => \"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'contao53.tl_user' doesn't exist\"]\n\nIn ExceptionConverter.php line 49:\n                                                                               \n  An exception occurred while executing a query: SQLSTATE[42S02]: Base table   \n  or view not found: 1146 Table 'contao53.tl_user' doesn't exist               \n                                                                               \n\nIn Exception.php line 28:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'contao53.tl_user  \n  ' doesn't exist                                                              \n                                                                               \n\nIn Connection.php line 71:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'contao53.tl_user  \n  ' doesn't exist                                                              \n                                                                               \n\ncontao:user:list [--column COLUMN] [--admins] [--format FORMAT]\n\n at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/api/Process/ContaoConsole.php:162)"} []
